version: "1.0"
name: "NSProject"
services:
    mysqlserver:
        container_name: MySQLServer
        build: ./MySQLServer/
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - WebNetwork
        expose:
            - 3306

    webserver:
        container_name: WebServer
        build: ./WebServer/
        depends_on:
            - mysqlserver
        environment:
            - NODE_ENV=production
        ports:
            - 8080:8080
        networks:
            - WebNetwork

    vulnerable:
        container_name: TomPC
        build: ./TomPC/
        tty: true
        networks:
            - LanNetwork
        expose:
            - 22

    pentesting:
        container_name: BobPC
        build: ./BobPC/
        tty: true
        networks:
            - LanNetwork
        ports:
            - 2222:22
networks:
    WebNetwork:
        driver: bridge
    LanNetwork:
        driver: bridge
