version: "3.9"
name: "NSProject"
services:
    mysqlserver:
        container_name: MySQLServer
        build: ./MySQLServer/
        networks:
            - WebNetwork
        expose:
            - 3306

    webserver:
        container_name: WebServer
        build: ./WebServer/
        depends_on:
            - mysqlserver
        environment:
            - NODE_ENV=production
        expose:
            - 8080
        networks:
            - WebNetwork
            - CompanyNetwork

    vulnerable:
        container_name: TomPC
        build: ./TomPC/
        tty: true
        networks:
            - EmployeeNetwork
            - CompanyNetwork
        expose:
            - 22

    pentesting:
        container_name: BobPC
        build: ./BobPC/
        tty: true
        networks:
            - EmployeeNetwork
            - CompanyNetwork
        ports:
            - 2222:22
networks:
    WebNetwork:
        driver: bridge
        ipam:
            config:
                - subnet
    EmployeeNetwork:
        driver: bridge
    CompanyNetwork:
        driver: bridge
    
