version: "3.9"
name: "NSProject"
services:
    mysqlserver:
        container_name: MySQLServer
        build: .dockerfiles/mysqlserver/
        networks:
            - WebNetwork
        expose:
            - 3306

    webserver:
        container_name: WebServer
        build: .dockerfiles/webserver/
        depends_on:
            - mysqlserver
        environment:
            - NODE_ENV=production
        expose:
            - 8080
        networks:
            - WebNetwork
            - CompanyNetwork

    vulnerable:
        container_name: TomPC
        build: .dockerfiles/tompc/
        tty: true
        networks:
            - EmployeeNetwork
            - CompanyNetwork
        expose:
            - 22

    pentesting:
        container_name: BobPC
        build: .dockerfiles/bobpc/
        tty: true
        networks:
            - EmployeeNetwork
            - CompanyNetwork
        ports:
            - 2222:22
networks:
    WebNetwork:
        driver: bridge
    EmployeeNetwork:
        driver: bridge
    CompanyNetwork:
        driver: bridge
    
